site_name: SteamFork Wiki
site_url: https://wiki.steamfork.org
repo_url: https://github.com/SteamFork/distribution
repo_name: distribution
copyright: Copyright Creative Commons Attribution-ShareAlike 4.0 International
theme:
  language: en
  name: material
  logo: _inc/images/logo.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: art-book
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: art-book-next
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Oxygen
    code: Oxygen Mono
  features:
    - navigation.top
    #- navigation.instant
    - navigation.sections
    - navigation.indexes
    - toc.follow 
    - search.suggest
    - content.tooltips
    - content.code.copy
    - content.code.annotate
markdown_extensions:
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      toc_depth: 3
      permalink: Â¶
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
extra_css:
  - _inc/css/custom.css
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/SteamFork/distribution
    #- icon: fontawesome/brands/discord 
    #  link: https://discord.gg/nou...
plugins:
  - search
  - glightbox
nav:
    - Home: index.md
    - FAQs: faqs.md
    - Troubleshooting: troubleshooting.md
    - Play:
      - Install: play/install.md
      - Software: play/verified-software.md 
      - Accessories: play/verified-accessories.md 
    - Contribute:
      - contribute/index.md
      - Code of Conduct: contribute/code-of-conduct.md
      - Build: contribute/build.md
      - Quirks: contribute/quirks.md
    - Devices:
      - devices/index.md
      - Anbernic:
        - Win600: devices/anbernic/win600.md
      - ASUS:
        - ROG Ally / Ally X: devices/asus/rog-ally.md
      - Atari:
        - VCS: devices/atari/vcs.md
      - AYANEO:
        - 2S: devices/ayaneo/ayaneo-2s.md
        - Air Plus: devices/ayaneo/air-plus.md
        - Flip KB: devices/ayaneo/flip-kb.md
      - AYN:
        - Loki Max: devices/ayn/loki-max.md
      - GPD:
        - Win 4 6800U: devices/gpd/win4-6800u.md
      - MSI:
        - Claw A1M: devices/msi/claw-a1m.md
        
